### ISSUE TITLE
상세  페이지 작업 

### ISSUE THREAD

**Issue by mugyeol** [cats-and-dogs-team3/cats-and-dogs-FE#8]
## Todo
- [ ] 좋아요 버튼 레이아웃
- [x] 댓글 작성 레이아웃
- [ ] api요청 및 렌더링 
- [ ] 회원가입 레이아웃
- [x] 디테일 페이지 반응형 적용
